### ISSUE TITLE
Usefulib Idea: Ternary converter!

### ISSUE THREAD

**Issue by AtomicCodeLegend** [hamdivazim/usefulib#11]
**Describe your idea**
Hi this is my first time contributing to usefulib! I think a good idea would be creating a function like `bin()` but for ternary (base 3) example:
```
input: 20
output: 202
```
Im thinking about opening a pull request with this idea but feel free to do the same but with other bases (like base 4 or base 5)!

**Comment by hamdivazim** [comment]
Hi @AtomicCodeLegend!

Amazing idea! It would be great if you open a pull request using this idea, and leaving other bases for others to try out! If you need help, I'll be happy to help out! Remember to read the contributing guidelines before opening a pull request :)

**Comment by AtomicCodeLegend** [comment]
thanks so much i will definitely open a pr soon

**Comment by ShadowStrike-Atomiser** [comment]
Hi @hamdivazim I also am a first-time contributor and have a similar idea that I want to open.

**Comment by AtomicCodeLegend** [comment]
cool

**Comment by hamdivazim** [comment]
Solved by #15 - thanks @ShadowStrike-Atomiser!
