### ISSUE TITLE
ModuleNotFound Error

### ISSUE THREAD

**Issue by MKM12345** [hamdivazim/usefulib#3]
I don't think this is of any use, but I have run the `py -m pip install usefulib` command in cmd, and it still gives an error of module not found. Am I missing something here?

**Comment by hamdivazim** [comment]
Can you send a screenshot of the issue? Is it a problem when you are installing the library or when you are importing in a script?

**Comment by MKM12345** [comment]
Sure

**Comment by MKM12345** [comment]
![image](https://user-images.githubusercontent.com/120132998/233854346-dcfc455b-fd37-40c4-bd4f-504811d2cf91.png)
![image](https://user-images.githubusercontent.com/120132998/233854361-810e5db7-866c-4714-9191-ddc11c5c0a74.png)
See this...

**Comment by hamdivazim** [comment]
Since you're in IDLE, use the hotkey Alt+M and type in `usefulib` to open the library. You should see the code below open. If see anything at all different, comment and paste in the contents of the file.
```
"""
usefulib v1.0.2
Copyright Hamd Waseem (https://github.com/hamdivazim) under the GNU Public License 3.0.

https://github.com/hamdivazim/usefulib
"""

__version__ = "1.0.2"

from ._usefulibs import *
```
I also uninstalled and reinstalled but seems to be working. Are you on Windows?

**Comment by MKM12345** [comment]
> Since you're in IDLE, use the hotkey Alt+M and type in `usefulib` to open the library. You should see the code below open. If see anything at all different, comment and paste in the contents of the file.
> 
> ```
> """
> usefulib v1.0.2
> Copyright Hamd Waseem (https://github.com/hamdivazim) under the GNU Public License 3.0.
> 
> https://github.com/hamdivazim/usefulib
> """
> 
> __version__ = "1.0.2"
> 
> from ._usefulibs import *
> ```
> 
> I also uninstalled and reinstalled but seems to be working. Are you on Windows?

Yes. and when I tried that. It says Module Not found.

**Comment by hamdivazim** [comment]
Follow the instructions properly:
1. Open IDLE and press Alt+M
2. In the popup that appears, type in `usefulib` and hit enter
3. You will see a file open. Compare its contents to the code above.

If the error is still occuring, make sure:
1. You are not installing into a virtual environment
2. Make sure your python versions are the same:
First into your terminal:
```
$ py --version
```
Then open IDLE. At the top there will be a version number. Make sure these are the same

**Comment by hamdivazim** [comment]
Hi, it seems there is a problem with all pip package installations (as you told me before) and has nothing to do with usefulib. Try diagnosing the issue and try again - it should work :)

**Comment by MKM12345** [comment]
Sorry - it has not been working

**Comment by MKM12345** [comment]
I just use Replit for this now

**Comment by hamdivazim** [comment]
Is this just an issue with usefulib or any module you install?
